export { default as DOC, xmlns } from './DOC.js'
export { default as HTML } from './HTML.js'
export { default as XHTML } from './XHTML.js'
export { default as XML } from './XML.js'
export { default as SVG } from './SVG.js'
export { default as CSS } from './CSS.js'
export * from './selectors.js'